region: us-west-2
bucket: immigranthealthai-data
iamRole: arn:aws:iam::123456789012:role/ImmigrantHealthAI-Role
encryption:
kmsKeyId: arn:aws:kms:us-west-2:123456789012:key/abcd1234-5678-90ef-ghij-klmn12345678
sseAlgorithm: AES256
hipaaCompliance:
enabled: true
auditLog: s3://immigranthealthai-audit/
