version: '3.8'
services:
api:
build: ./src/api
ports:
- "3000:3000"
environment:
- NODE_ENV=production
- AES_KEY=${AES_KEY}
- FDA_API_KEY=${FDA_API_KEY}
volumes:
- ./data:/app/data
depends_on:
- db
frontend:
build: ./src/frontend
ports:
- "80:80"
environment:
- REACT_APP_API_URL=http://api:3000
db:
image: postgres:15
environment:
- POSTGRES_DB=immigranthealthai
- POSTGRES_USER=admin
- POSTGRES_PASSWORD=secret
volumes:
- db-data:/var/lib/postgresql/data
volumes:
db-data:

